# Generated by Django 4.0.3 on 2022-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
