# Generated by Django 4.0.3 on 2022-03-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_alter_userprofile_client_alter_userprofile_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='mechanics.mechanic'),
        ),
    ]
