# Generated by Django 4.0.3 on 2022-03-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0003_rename_contact_user_name_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Username',
        ),
    ]
